# Generated by Django 4.0.3 on 2022-04-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30, verbose_name="trainer's nickname")),
                ('first_name', models.CharField(max_length=30, verbose_name="trainer's first name")),
                ('last_name', models.CharField(max_length=30, verbose_name="trainer's second name")),
                ('email', models.CharField(max_length=30, verbose_name="trainer's email")),
                ('password', models.CharField(max_length=8, verbose_name='********')),
                ('team', models.CharField(choices=[('V', 'Team Valor'), ('I', 'Team Instinct'), ('M', 'Team Mystic')], default='', max_length=1)),
                ('pokemons_owned', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trainer',
                'verbose_name_plural': 'Trainers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('base_experience', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('trainer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Pokemon', to='api.trainer')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
                'ordering': ['id'],
            },
        ),
    ]
