# Generated by Django 4.0.3 on 2022-04-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='trainer_id',
        ),
        migrations.AddField(
            model_name='trainer',
            name='pokemon_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Pokemon', to='api.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='base_experience',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='is_default',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
