# Generated by Django 4.0.3 on 2022-04-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pokemon_trainer_id_trainer_pokemon_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='pokemon_id',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Trainer', to='api.trainer'),
        ),
    ]
