# Generated by Django 4.0.3 on 2022-04-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_trainer_pokemon_id_pokemon_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='trainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pokemon', to='api.trainer'),
        ),
    ]
