# Generated by Django 4.0.3 on 2022-04-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pokemon_trainer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='pokemon',
            field=models.JSONField(default={}),
        ),
    ]
