# Generated by Django 4.0.3 on 2022-04-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trainer_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='pokemon',
            field=models.JSONField(default=dict),
        ),
    ]
