# Generated by Django 4.0.3 on 2022-04-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_trainer_pokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='pokemon',
            new_name='pokemons',
        ),
    ]
