# Generated by Django 4.0.3 on 2022-04-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_pokemon_trainer_pokemons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='pokemons',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='trainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trainer'),
        ),
    ]
