# Generated by Django 4.0.3 on 2022-04-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_trainer_pokemons_alter_pokemon_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='trainer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trainer'),
        ),
    ]
